before:
  hooks:
    - go mod tidy

builds:
  - id: metacritic-api
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - { goos: windows, goarch: arm }
      - { goos: windows, goarch: arm64 }
      - { goos: darwin, goarch: arm }
      - { goos: freebsd, goarch: arm }
      - { goos: freebsd, goarch: arm64 }
    main: cmd/metacritic-api/main.go
    binary: metacritic-api

archives:
  - id: metacritic-api
    builds:
      - metacritic-api
    files:
      - none*
    replacements:
      amd64: x86_64

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/s0up4200/metacritic-api/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
